install.packages("tidyverse")
install.packages("tidyr")
install.packages("phyloseq")
install.packages("cowplot")
install.packages("stringr")
install.packages("mapdata")
install.packages("sf")
install.packages("sp")
install.packages("rgdal")
install.packages("terra")
install.packages("viridis")
install.packages("remotes")   ## run this line if you do not already have remotes installed
library(remotes)
remotes::install_github("adw96/breakaway")
remotes::install_github("adw96/DivNet")
library(DivNet)
if (!requireNamespace("BiocManager", quietly = TRUE)) install.packages("BiocManager")
BiocManager::install(c("phyloseq", "microbiome", "ComplexHeatmap"), update = FALSE)
install.packages(
  "microViz",
  repos = c(davidbarnett = "https://david-barnett.r-universe.dev", getOption("repos"))
)
library(microViz)
if (!require("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install("decontam")
library(decontam)
library(zCompositions)
devtools::install_github("tpq/propr")
library("propr")
BiocManager::install("ALDEx2")
BiocManager::install("EnhancedVolcano")
install.packages("vegan")
install.packages("repmis")